### PR TITLE
Added option to prettyprint d.dump() XML hierarchy

### PR DESCRIPTION
**Pull request by ericvalente**
I found that d.dump() was very difficult to read, added ability to pretty print the XML dump.

### CODE REVIEW

**Comment by ericvalente** [comment]
Hi there,

Getting this error in travis when running through your unit tests: 

======================================================================
ERROR: test_dump (test_device.TestDevice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/xiaocong/uiautomator/test/test_device.py", line 51, in test_dump
    self.assertEqual(self.device.dump("/tmp/test.xml"), "<?xml>")
  File "/home/travis/build/xiaocong/uiautomator/uiautomator/__init__.py", line 608, in dump
    xml_text = xml.dom.minidom.parseString(str(content))
  File "/opt/python/2.7.9/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/opt/python/2.7.9/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/opt/python/2.7.9/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: not well-formed (invalid token): line 1, column 5
----------------------------------------------------------------------

**Comment by ericvalente** [comment]
@xiaocong just curious if you have any thoughts on the above PR?

**Comment by xiaocong** [comment]
Thank @ericvalente

**Comment by ericvalente** [comment]
That's not the case for me in iPython and iPython notebook:

image

image

**Pull request merged**
